---
- name: Crear Host en el Inventario
  hosts: localhost
  gather_facts: no
  vars:
    name: "{{ lookup('env', 'name') }}"  # Obtener el valor de la variable del entorno

  tasks:
    - name: Crear el host si no existe en el inventario
      add_host:
        name: "{{ name }}"
        groups: "Linux_Machines"
