---
- name: Crear Host en el Inventario
  hosts: localhost
  gather_facts: no
  vars:
    ip: "{{ lookup('env', 'ip') }}"  # Obtener el valor de la variable del entorno

  tasks:
    - name: Crear el host si no existe en el inventario
      add_host:
        name: "{{ ip }}"
        groups: "Linux_Machines"
