---
- name: Escaneo de Hardening en Linux
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Definir el nombre del host dinámicamente
      set_fact:
        target_host: "mi_servidor"  # Cambia "mi_servidor" al nombre del host que desees

    - name: Verificar si el host existe en el inventario
      command: ansible-inventory --list
      register: inventory_list
      changed_when: false
      ignore_errors: true

    - name: Crear el host si no existe en el inventario
      add_host:
        name: "{{ target_host }}"
        groups: "nuevo_grupo"
      when: "'{{ target_host }}' not in inventory_list.stdout | from_json | default({})"

- name: Realizar el escaneo de hardening
  hosts: "{{ target_host }}"
  become: yes
  tasks:
    - name: Actualizar paquetes del sistema (solo para sistemas Debian)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Ejecutar el escaneo Lynis
      command: lynis audit system
      register: lynis_result
      ignore_errors: yes
      changed_when: false

    - name: Imprimir resultados del escaneo
      debug:
        var: lynis_result.stdout_lines

    # Puedes agregar más tareas de hardening aquí según tus necesidades específicas.
