---
- name: Escaneo de Hardening en Linux
  hosts: "{{ name }}"
  become: yes
  tasks:
    - name: Actualizar paquetes del sistema (solo para sistemas Debian)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Ejecutar el escaneo Lynis
      command: lynis audit system
      register: lynis_result
      ignore_errors: yes
      changed_when: false

    - name: Imprimir resultados del escaneo
      debug:
        var: lynis_result.stdout_lines

    # Puedes agregar más tareas de hardening aquí según tus necesidades específicas.
