---
- name: Update and reboot
  hosts: Linux_Machines  # Cambia esto al grupo de hosts de Ubuntu en tu inventario
  gather_facts: yes  # Cambia esto a "yes" si deseas recopilar información sobre los hosts

  tasks:
    - name: Update package cache on Ubuntu
      apt:
        update_cache: yes
      become: yes  # Ejecutar como superusuario para actualizar la caché de paquetes

    - name: Upgrade all packages on Ubuntu
      apt:
        name: '*'
        state: latest  # Utiliza "latest" para actualizar los paquetes en Ubuntu
        autoclean: yes  # Opcional: para limpiar paquetes obsoletos
      become: yes

    - name: Reboot servers on Ubuntu
      reboot:
        pre_reboot_delay: 90
        msg: "!!!Attention, server will be rebooted in 90 seconds!!!"
      become: yes
